# Welcome to Jekyll!

# Website settings
title: "Tom de Geus"
description: "Personal website"
keywords: "Publications,Statistics,Materials"
baseurl: "/"
url: "http://www.geus.me"

# author
author:
  name: 'Tom de Geus'
  first_name: 'Tom'
  last_name: 'de Geus'
  email: 'tom@geus.me'
  linkedin_username: 'tdegeus'
  github_username: 'tdegeus'
  avatar: 'static/img/landing/Tom.jpg'
  desc: |
    I am a scientist in the fields of mechanics and materials science.
    My particular interests lie in computational mechanics, damage and fracture,
    and tribology.
    <br /><br />
    ResearchID: <a target="_blank" href="http://www.researcherid.com/rid/B-8223-2016"> B-8223-2016</a>,
    ORCID iD: <a target="_blank" href="https://orcid.org/0000-0002-1694-3375"> 0000-0002-1694-3375</a>.
    <br />
    Please find me on <a target="_blank" href=" http://arxiv.org/a/degeus_t_1"> arXiv</a>, <a target="_blank" href=" https://scholar.google.ch/citations?user=e5yVf8AAAAAJ&hl=en"> Google Scholar</a>, and
    <a target="_blank" href="https://www.researchgate.net/profile/Tom_De_Geus"> ResearchGate</a>
# blog image path
img_path: 'static/img/blog'

# build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
