name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:

  standard:

    runs-on: [ubuntu-latest]

    defaults:
      run:
        shell: bash -e -l {0}

    steps:

    - name: Clone this library
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        init-shell: bash
        cache-downloads: true
        post-cleanup: all

    - name: Setup TeXLive
      uses: xu-cheng/latex-action@v4

    - name: Install TeX packages
      run: tlmgr install array authblk biblatex bibunits caption cleveref enumitem environ etoolbox eurosym fira fontawesome5 fontaxes framed hyperref latexmk listings listingsutf8 marvosym microtype newfloat pdfcol pgf ragged2e scheme-basic setspace sttools subfig tcolorbox tikzfill titlesec uri xcolor xkeyval

    - name: Clone pybtex
      run: git clone https://bitbucket.org/pybtex-devs/pybtex.git

    - name: Install pybtex locally
      working-directory: pybtex
      run: python -m pip install . -v --no-build-isolation

    - name: Make
      run: make html

    - name: Setup custom domain
      run: echo "www.geus.me" > _build/html/CNAME

    - uses: actions/upload-artifact@v4
      with:
        name: preview
        path: _build/html
        retention-days: 1

    - name: Deploy to GitHub Pages
      if: success() && github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: gh-pages
        build_dir: _build/html
        jekyll: false
        keep_history: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
