name: gh-pages

on:
  push:
    branches:
      - master

jobs:

  jekyll:

    runs-on: ubuntu-latest

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Get gems from cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Deploy to GitHub Pages
      uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        target_branch: 'gh-pages'
